ТЗ №9
RaisaRS/java-filmorate pull request #2
Opened 2023-04-09 10:59 UTC by RaisaRS

готово

2023-04-10 21:02 UTC, RaisaRS commented
задание готово к проверке

2023-04-11 07:31 UTC, alexache requested changes

2023-04-11 07:31 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +        log.info("PUT request received: {}", film);
namedFilms при обновлении не используется?

2023-04-11 07:31 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    public Map<Integer, Film> getFilms() {
Какой-то лишний метод

2023-04-11 07:31 UTC, alexache commented on src/test/java/ru/yandex/practicum/filmorate/FilmControllerTest.java
> +     static  FilmController filmController;
Модификатор доступа

2023-04-11 07:31 UTC, alexache commented on src/test/java/ru/yandex/practicum/filmorate/FilmControllerTest.java
> +     private static Film film;
Что-то с отступами

2023-04-11 07:31 UTC, alexache commented on src/test/java/ru/yandex/practicum/filmorate/FilmControllerTest.java
> +        Exception exception =  assertThrows(ValidationException.class, () -> filmController.putFilm(film));
Для проверки валидации аннотациями тоже есть способ через создание валидатора и его вызова

2023-04-11 17:35 UTC, RaisaRS commented on src/test/java/ru/yandex/practicum/filmorate/FilmControllerTest.java
> +     static  FilmController filmController;
private - исправила

2023-04-11 18:21 UTC, RaisaRS commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    public Map<Integer, Film> getFilms() {
нет, он используется у меня в тестах:
shouldAddFilmTest() - строка 40
 @AfterEach
    void finishedTest() {
        filmController.getNameFilms().clear();
        filmController.getFilms().clear();
    } - строка 28

2023-04-11 19:06 UTC, RaisaRS commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +        log.info("PUT request received: {}", film);
добавила

2023-04-11 21:03 UTC, RaisaRS commented
готово

2023-04-12 17:20 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    public Map<Integer, Film> getFilms() {
Это очень плохая практика писать методы для тестов, такого не должно быть

2023-04-12 17:25 UTC, alexache approved these changes

2023-04-12 17:25 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    //@NotNull(message = "Название фильма не может отстутствовать")
Закомментированный код лучше удалять

2023-04-12 17:25 UTC, alexache commented on src/test/java/ru/yandex/practicum/filmorate/FilmControllerTest.java
> +     private static Film film;
Поменялось - у полей

2023-04-12 18:17 UTC, merged